config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        registrations: 'users/registrations'
  }
	root 'home#index'

	resources :users, only: [:index]

	resources :boats

	resources :jobs

  resources :contracts, only: [:create, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
	belongs_to :user
	has_many :contracts, dependent: :destroy
	has_many :boats, through: :contracts

	has_attached_file :avatar, styles: { medium: "400x400>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	validates :description, :origin, :destination, :cost, :load, presence: true
	validates :description, length: {minimum: 50}
	validates :cost, :load, numericality: true
	validates :cost, numericality: {greater_than_or_equal_to: 1000}
	validates :origin, inclusion: { in: ['Los Angeles, CA', 'San Diego, CA', 'Sydney, AU', 'Tokyo, JP', 'Tianjin, CN'],
    message: "%{value} is not a valid destination" }
  validates :destination, inclusion: { in: ['Los Angeles, CA', 'San Diego, CA', 'Sydney, AU', 'Tokyo, JP', 'Tianjin, CN'],
    message: "%{value} is not a valid destination" }
  # validates :destination, :origin_different_from_destination

  # def origin_different_from_destination
  #   if origin == destination
  #     errors.add(:destination, "can't be the same as origin")
  #   end
  # end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
    @contract = Contract.new
  end

  def new
    @job = Job.new
  end

  def create
    @job = current_user.jobs.new(job_params)
    respond_to do |format|
      Job.new(job_params)
      if @job.save
        format.js
        format.html {redirect_to jobs_path}
      else
        render new_job_path
      end
    end 
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
    @job = Job.find(params[:id])  
  end

  def update
    @job = Job.find(params[:id])
    respond_to do |format|
      @job.update(job_params)
      format.js 
    end
  end

  def destroy
    respond_to do |format|
      @job = Job.find(params[:id]).destroy
      format.js
      format.html
    end
  end

  private

  def job_params
    params.require(:job).permit(:name, :description, :origin, :destination, :cost, :load, :user_id, :avatar)
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<% if @job.errors.full_messages.any? %>
	<ul>
		<% @job.errors.full_messages.each do |error| %>
			<li><%= error %></li>
		<% end %>
	</ul>
<% end %>

<%= form_with model: @job, html: { multipart: true }, local: true do |f| %>
<%= f.hidden_field :user_id, value: current_user.id %>
	<%= f.text_field :name, placeholder: 'Name' %>
	<%= f.text_area :description, placeholder: 'Description' %>
	<%= f.text_field :cost, placeholder: 'Cost' %>
	<%= f.text_field :load, placeholder: 'Load' %>

	<div class="field">
	  <% if @job.avatar.file? %>
	    <p>Your current image: </p>
	    <%= image_tag current_user.avatar.url(:medium) %>
	   <% end %>
	    <%= f.file_field :avatar %>
  </div>

	<%= f.select(:origin) do %>
  	<option value="" disabled selected>Job Origin</option>
  	
		<% [['Los Angeles, CA'], ['San Diego, CA'], ['Sydney, AU'], ['Tokyo, JP'], ['Tianjin, CN']].each do |c| %>
			<option value="<%= c.first %>"><%= c.first %></option>
   	<% end %>
  <% end %>

  <%= f.select(:destination) do %>
  	<option value="" disabled selected>Job Destination</option>
  	
		<% [['Los Angeles, CA'], ['San Diego, CA'], ['Sydney, AU'], ['Tokyo, JP'], ['Tianjin, CN']].each do |c| %>
			<option value="<%= c.first %>"><%= c.first %></option>
   	<% end %>
  <% end %>
	<%= f.submit "Add Job", :class => "btn waves-effect waves-light blue darken-3" %>
<% end %>

app/views/jobs/_job.html.erb
<div class="col-3 job" id="job-<%= job.id %>">
	<div class="card">
    <div class="view overlay hm-white-slight">
      <%= image_tag job.avatar.url(:medium) %>
    </div>
    <div class="card-body">
    	<%= form_with model: job, class: "job_edit_form" do |f| %>
      <h4 class="card-title"><%= job.name %></h4>
      <p class="card-text">
      	<ul>
      		<%= f.text_area :description, placeholder: job.description, disabled: true, class: "job_edit_field first_field" %>
      		<%= f.select(:location) do %>
  					<option value="" disabled selected> <%= job.origin %></option>
						<% [['Los Angeles, CA'], ['San Diego, CA'], ['Sydney, AU'], ['Tokyo, JP'], ['Tianjin, CN']].each do |c| %>
							<option value="<%= c.first %>"><%= c.first %></option>
   					<% end %>
  				<% end %><br/>
      		<%= f.select(:destination) do %>
  					<option value="" disabled selected> <%= job.destination %></option>
						<% [['Los Angeles, CA'], ['San Diego, CA'], ['Sydney, AU'], ['Tokyo, JP'], ['Tianjin, CN']].each do |c| %>
							<option value="<%= c.first %>"><%= c.first %></option>
   					<% end %>
  				<% end %>
      		<%= f.text_field :cost, placeholder: job.cost, disabled: true, class: "job_edit_field" %>
      		<%= f.text_field :load, placeholder: job.load, disabled: true, class: "job_edit_field" %>
      	</ul>
      </p>
      <% if current_user %>
      <button class="edit_job">Edit Job</button>
      <%= f.submit "Save Job", class: "save_job" %>
      <% end %>
      <% end %>
			<% if current_user %>
				<h3>Quick Add</h3>
				<%= form_with model: @contract, class: "contract_form", data: {"reference-id": "job-#{job.id}"} do |f| %>
					<%= f.hidden_field :job_id, value: job.id %>
					<%= f.select(:boat_id) do %>
						<option value="" disabled selected>Select a Boat</option>
						<% current_user.boats.each do |boat| %>
							<option value="<%= boat.id %>"><%= boat.name %> | Capacity: <%= boat.capacity %></option>
						<% end %>
					<% end %>
					<%= f.submit "Add Boat", class: "contract_submit" %>
				<% end %>
			<% end %>
			<% if job.contracts.any? %>
			<h3>Contracted Boats</h3>
			<% end %>
      <div class="contracts_container">
        <%= render 'jobs/job_contracts', job: job %>
      </div>
			<%= link_to "Delete Job", job_path(job), method: :delete, remote: true, class: "delete_job" %>
    </div>
	</div>
</div>

app/views/jobs/_job_contracts.html.erb
<ul class="contracts">
	<% job.contracts.each do |contract| %>
		<p class="contract"><%= contract.boat.name %> | Capacity: <%= contract.boat.capacity %> <%= link_to "Delete", contract_path(contract), method: :delete, remote: true, class: "delete_contract" %></p>
	<% end %>
</ul>

app/views/jobs/create.html.erb
<div class="container">
	<div class="row">
		<div class="col"></div>
		<div class="col-10">
			<h2>New Job</h2>
      <%= render 'form' %>
		</div>
		<div class="col"></div>
	</div>
</div>

app/views/jobs/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col"></div>
		<div class="col-10">
			<h2>Edit Job</h2>
			<%= render 'form' %>
		</div>
		<div class="col"></div>
	</div>
</div>

app/views/jobs/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-3">
			<div class="card_light_blue">
		    <div class="view overlay hm-white-slight">
	        <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20%287%29.jpg" class="img-fluid" alt="">
	        <a href="#">
	          <div class="mask"></div>
	        </a>
		    </div>
		    <div class="card-body">
	        <h4 class="card-title white-text">New Job</h4>
	        <p class="card-text white-text">Select this option to create a new job for your profile</p>
	        <%= link_to "New Job", new_job_path, class: "btn btn-primary new_boat" %>
		    </div>
			</div>
		</div>
		<% @jobs.each do |job| %>
			<%= render job %>
		<% end %>
	</div>
</div>

app/views/jobs/new.html.erb
<div class="container">
	<div class="row">
		<div class="col"></div>
		<div class="col-10">
			<h2>New Job</h2>
      <%= render 'form' %>
		</div>
		<div class="col"></div>
	</div>
</div>

app/views/jobs/show.html.erb
<div class="card">
  <div class="view overlay hm-white-slight">
    <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20%287%29.jpg" class="img-fluid" alt="">
    <a href="#">
      <div class="mask"></div>
    </a>
  </div>
  <div class="card-body">
    <h4 class="card-title"><%= @job.description %></h4>
    <p class="card-text">
    	<ul>
    		<li>Origin: <%= @job.origin %></li>
    		<li>Destination: <%= @job.destination %></li>
    		<li>Cost: <%= @job.cost %></li>
    		<li>Load: <%= @job.load %></li>
    	</ul>
    </p>
		<% form_with contracts_path do |f| %>
			<%= f.hidden_field :job_id %>
			<%= f.submit "Submit" %>
		<% end %>
  </div>
</div>

app/views/jobs/update.html.erb
<h1>Jobs#update</h1>
<p>Find me in app/views/jobs/update.html.erb</p>