config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        registrations: 'users/registrations'
  }
	root 'home#index'

	resources :users, only: [:index]

	resources :boats

	resources :jobs

  resources :contracts, only: [:create, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :user
  has_many :contracts, dependent: :destroy
  has_many :jobs, through: :contracts

	has_attached_file :avatar, styles: { medium: "400x400>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates :name, presence: true, uniqueness: true
  validates :capacity, presence: true, numericality: true
  validates :location, presence: true
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  def index
    @boats = Boat.all
    @contract = Contract.new
    @boat = @contract.boat
  end

  def new
    @boat = Boat.new
  end

  def create
    @boat = current_user.boats.new(boat_params)
    respond_to do |format|
      Boat.new(boat_params)
      if @boat.save
        format.js
        format.html {redirect_to boats_path}
      else
        render new_boat_path
      end
    end 
  end

  def show
    @boat = Boat.find(params[:id])
  end

  def edit
    @boat = Boat.find(params[:id])
  end

  def update
    @boat = Boat.find(params[:id])
    respond_to do |format|
      @boat.update(boat_params)
      format.js
    end
  end

  def destroy
    respond_to do |format|
      @boat = Boat.find(params[:id]).destroy
      format.js
      format.html
    end
  end

  private

  def boat_params
    params.require(:boat).permit(:name, :capacity, :location, :avatar)
  end
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/views/boats/_boat.html.erb
<div class="col-3 boat" id="boat-<%= boat.id %>">
	<div class="card">
    <div class="view overlay hm-white-slight">
     <%= image_tag boat.avatar.url(:medium) %>
    </div>
    <div class="card-body">
    	<%= form_with model: boat, class: "boat_edit_form" do |f| %>
	      <h4 class="card-title"><%= boat.name %></h4>
	      <p class="card-text">
	      	<ul>
	      		<%= f.select(:location) do %>
	  					<option value="" disabled selected> <%= boat.location %></option>
							<% [['Los Angeles, CA'], ['San Diego, CA'], ['Sydney, AU'], ['Tokyo, JP'], ['Tianjin, CN']].each do |c| %>
								<option value="<%= c.first %>"><%= c.first %></option>
	   					<% end %>
	  				<% end %>
	      		<%= f.text_field :capacity, placeholder: boat.capacity, disabled: true, class: "boat_edit_field" %>
	      	</ul>
	      </p>
	      <button class="edit_boat">Edit Boat</button>
	      <%= f.submit "Save Boat", class: "save_boat" %>
      <% end %>
			<% if current_user %>
				<h3>Quick Add</h3>
				<%= form_with model: @contract, class: "contract_form", data: {"reference-id": "boat-#{boat.id}"} do |f| %>
					<%= f.hidden_field :boat_id, value: boat.id %>
					<%= f.select(:job_id) do %>
						<option value="" disabled selected>Select a Job</option>
						<% current_user.jobs.each do |job| %>
							<option value="<%= job.id %>"><%= job.name %> | Load: <%= job.load %></option>
						<% end %>
					<% end %>
					<%= f.submit "Add Job", class: "contract_submit" %>
				<% end %>
			<% end %>
			<% if boat.contracts.any? %>
			<h3>Contracted Jobs</h3>
			<% end %>
			<div class="contracts_container">
				<%= render 'boats/boat_contracts', boat: boat %>
			</div>
			<%= link_to "Delete Boat", boat_path(boat), method: :delete, remote: true %>
    </div>
	</div>
</div>

app/views/boats/_boat_contracts.html.erb
<ul class="contracts">
	<% boat.contracts.each do |contract| %>
		<p class="contract"><%= contract.job.name %> | Load: <%= contract.job.load %> <%= link_to "Delete", contract_path(contract), method: :delete, class: 'delete_contract', remote: true %></p>
	<% end %>
</ul>

app/views/boats/_form.html.erb
<% if @boat.errors.full_messages.any? %>
	<ul>
		<% @boat.errors.full_messages.each do |error| %>
			<li><%= error %></li>
		<% end %>
	</ul>
<% end %>

<%= form_with model: @boat, html: { multipart: true }, local: true do |f| %>
<%= f.hidden_field :user_id, value: current_user.id %>
	<%= f.text_field :name, placeholder: 'Name' %>
	<%= f.text_field :capacity, placeholder: 'Capacity' %>

	<div class="field">
    <% if @boat.avatar.file? %>
      <p>Your current image: </p>
      <%= image_tag current_user.avatar.url(:medium) %>
    	<% end %>
      <%= f.file_field :avatar %>
  </div>

	<%= f.select(:location) do %>
  	<option value="" disabled selected>Ship's Current Location</option>
  	
		<% [['Los Angeles, CA'], ['San Diego, CA'], ['Sydney, AU'], ['Tokyo, JP'], ['Tianjin, CN']].each do |c| %>
			<option value="<%= c.first %>"><%= c.first %></option>
   	<% end %>
  <% end %> <br/>
	<%= f.submit "Add Ship To Inventory", class: "btn waves-effect waves-light blue darken-4" %>
<% end %>

app/views/boats/create.html.erb
<h1>Boats#create</h1>
<p>Find me in app/views/boats/create.html.erb</p>

app/views/boats/destroy.html.erb
<h1>Boats#destroy</h1>
<p>Find me in app/views/boats/destroy.html.erb</p>

app/views/boats/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col"></div>
		<div class="col-10">
			<h2>Edit Boat</h2>
			<%= render 'form' %>
		</div>
		<div class="col"></div>
	</div>
</div>

app/views/boats/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-3">
			<div class="card card_blue">
		    <div class="view overlay hm-white-slight">
	        <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20%287%29.jpg" class="img-fluid" alt="">
	        <a href="#">
	          <div class="mask"></div>
	        </a>
		    </div>
		    <div class="card-body">
	        <h4 class="card-title white-text">New Boat</h4>
	        <p class="card-text white-text">Select this option to create a new boat for your profile</p>
	        <%= link_to "New Boat", new_boat_path, class: "btn btn-primary" %>
		    </div>
			</div>
		</div>
		<% @boats.each do |boat| %>
			<%= render boat %>
		<% end %>
	</div>
</div>

app/views/boats/new.html.erb
<div class="container">
	<div class="row">
		<div class="col"></div>
		<div class="col-10">
			<h2>New Boat</h2>
			<%= render 'form' %>
		</div>
		<div class="col"></div>
	</div>
</div>

app/views/boats/show.html.erb
<div class="card">
  <div class="view overlay hm-white-slight">
    <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20%287%29.jpg" class="img-fluid" alt="">
    <a href="#">
      <div class="mask"></div>
    </a>
  </div>
  <div class="card-body">
    <h4 class="card-title"><%= @boat.name %></h4>
    <p class="card-text">
    	<ul>
    		<li>Capacity: <%= @boat.capacity %></li>
    		<li>Location: <%= @boat.location %></li>
    	</ul>
    </p>
  </div>
</div>

app/views/boats/update.html.erb
<h1>Boats#update</h1>
<p>Find me in app/views/boats/update.html.erb</p>